cloudscape-design/collection-hooks

src/__tests__/stubs.tsx, src/interfaces.ts
This property is part of the interface, but not passed in the return value. It has caused confusion about the existence on client side filtering, which is why we are removing it. 
=> chore: Remove unused `loading` property

.eslintrc, src/__tests__/operations/property-filter.test.ts, src/index.ts, src/interfaces.ts, src/operations/property-filter.ts, src/utils.ts
Exporting property-filter props to deduplicate their definition between components and collection-hooks. Once merged, the types will be consumed by the components package, replacing the existing ones here: https://github.com/cloudscape-design/components/blob/main/src/property-filter/interfaces.ts
=> Export property filter props to be used in components

src/__tests__/operations/property-filter.test.ts, src/__tests__/stubs.tsx, src/__tests__/use-collection.test.tsx, src/interfaces.ts, src/use-collection-state.ts, src/use-collection.ts, src/utils.ts
Make filtering property a generic type for use-collection input/output to allow property filter extension in components.
Depends on https://github.com/cloudscape-design/components/pull/198
=> Make filtering property a generic type for use-collection input/output

src/interfaces.ts
Current code fails in this use-case:
```js
const interceptedOnSelectionChange: TableProps['onSelectionChange'] = event => {
collectionProps.onSelectionChange(event); // assignability error here, because our argument is not cancelable, but collection hook wants it cancelable
myCustomOnChange(event);
}
<Table {...collectionProps} onSelectionChange={interceptedOnSelectionChange} />
```
=> fix types assignability for custom event arguments

src/__tests__/operations/property-filter.test.ts, src/__tests__/stubs.tsx, src/__tests__/use-collection.test.tsx, src/interfaces.ts, src/use-collection-state.ts, src/use-collection.ts, src/utils.ts
This reverts commit ad5bd0759d9e7387dbf7f5db949301fc153b86bb.
Reverting as it causes TS errors on customers end.
=> Revert "Make filtering property a generic type for use-collection input/output

src/interfaces.ts
When the form is rendered inside the token editor there is no filter possible. Making it `undefined` makes this better explicit.
=> Make custom operator form filter optional

src/__tests__/operations/property-filter.test.ts, src/operations/property-filter.ts
Preserve original item value when filtering with custom operator matcher. W/o the change the fasly item values such as `false` can be formatted to a string, affecting the match result.
=> Preserve original item value when filtering with custom operator matcher

src/__tests__/operations/combined.test.ts, src/interfaces.ts, src/operations/index.ts, src/use-collection.ts
Exposed unpaginated items to be used for data export.
Ticket: AWSUI-19321
=> Expose unpaginated items in the use collection result

src/__tests__/stubs.tsx, src/__tests__/use-collection.test.tsx, src/interfaces.ts, src/use-collection.ts, src/utils.ts
Add `firstIndex` `totalItemsCount`  properties to `collectionProps`
these properties will be used in https://github.com/cloudscape-design/components/pull/521
=> feat: Add firstIndex and totalItems count to collectionProps

src/__tests__/operations/property-filter.test.ts, src/interfaces.ts, src/operations/property-filter.ts
Introduced the new starts-with operator (symbol `^`) and changed the operator type to accept any strings which is to support future operator extensions with no changes required for the consumers.
=> feat: Added starts-with property filter operator

src/__tests__/operations/property-filter.test.ts, src/operations/property-filter.ts
Addressed feedback on https://github.com/cloudscape-design/collection-hooks/pull/51
=> chore: Throw an error when matching against an unsupported property filter operator

src/__tests__/operations/legacy.test.ts, src/operations/filter.ts, src/operations/property-filter.ts, src/operations/sort.ts
Restoring until we find a better way to share this code.
=> fix: Restore some internal exports used by customers

src/__tests__/operations/paginate.test.ts, src/operations/pagination.ts
*Issue #, if available:* AWSUI-27293
The `currentPageIndex` parameter for pagination is a `number` type, which technically means it accepts `NaN` as a value. In that case we should fall back to page 1, like we do when the page number is out of range.
=> fix: Fix handling of NaN for `currentPageIndex`

src/__tests__/operations/property-filter.test.ts, src/index.ts, src/interfaces.ts, src/operations/property-filter.ts, src/utils.ts
*Description of changes:* Adding the ability to customize free text filtering operators for the Property Filter, just like every other property operator.
See: k6RfAb8hHR1t
Prototyping this quickly showed the agreed upon API was a perfect 1:1 match for this package, and the change was small enough to jump straight to PR.
Corresponding code change on `@cloudscape-design/components` has [a first prototype here](https://github.com/cloudscape-design/components/compare/main...eudes/property-filter-free-text-operators), pending new unit tests and probably more dev app updates. But I can't submit a clean PR for it until this PR is merged given the direct dependency.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
=> feat: Configurable operators for free text filtering in property filter

src/__tests__/use-collection.test.tsx, src/interfaces.ts, src/utils.ts
The `firstIndex` and `totalItemsCount` properties are used in the Table and Cards components. The properties are needed for `renderAriaLive` announcements and to assign `aria-rowcount` and `aria-rowindex`. While the latter can be omitted when there is no pagination, the live announcements are important regardless because those include the change of the total items count when filtering.
=> fix: Always provide firstIndex and totalItemsCount in collection result

package-lock.json, package.json, src/__tests__/date-utils/compare-dates.test.ts, src/__tests__/date-utils/parse-iso-date.test.ts, src/__tests__/operations/combined.test.ts, src/__tests__/operations/filter.test.ts, src/__tests__/operations/paginate.test.ts, src/__tests__/operations/process-selected.test.ts, src/__tests__/operations/property-filter.test.ts, src/__tests__/operations/sort.test.ts, src/__tests__/setup.ts, src/__tests__/use-collection-expadable-rows.test.tsx, src/__tests__/use-collection.test.tsx, vite.config.ts
Migrate to vitest - Faster, more modern, less dependencies, esm support.
Comparing previous runs, this is about 30% faster and reduces the time for `npm run test` from ~15s to ~9s. 
=> chore: Migrate to vitest

src/__tests__/use-collection-expadable-rows.test.tsx, src/utils.ts
Fixing a bug when selection config w/o trackBy overrides expandableRows.trackBy with undefined which breaks expandable rows matching in the table.
*Issue #, if available:*
=> fix: Expandable rows trackBy to not be overridden with undefined when selection is present

src/__tests__/operations/property-filter.test.ts, src/index.ts, src/interfaces.ts, src/logging.ts, src/operations/property-filter.ts
The PR introduces tokenType="enum" support for property filter. The setting is to be used by the property filter component (see https://github.com/cloudscape-design/components/pull/2739) to replace the default autosuggest form with a multi-select one, use a default formatter to join the values and to save the token value as an array. In collection hooks the token value is then assumed to be an array and a different matching logic is used for "=" and "!=" operators.
Rel: [Tz3OAr3i2ni1]
=> feat: Property filter token type Enum

package-lock.json, package.json, src/logging.ts, src/types.ts, tsconfig.json, tsconfig.unit.json
*Issue #, if available:*
Align configuration with cloudscape-design/components and fix some build issues
Dry-runs: 7169913711, 7169914866
=> fix: Upgrade typescript configuration

src/__tests__/operations/filter.test.ts, src/operations/filter.ts
*Issue #, if available:* AWSUI-60174, AWSUI-19651
Update so that auto-filtering only uses primitive values, to avoid e.g. "object" matching {}, or stringified date object being matched by timezone name.
=> fix: Ensure that auto-filtering only matches primitive values

src/__tests__/operations/paginate.test.ts, src/__tests__/stubs.tsx, src/__tests__/use-collection.test.tsx, src/operations/pagination.ts
Remove logic that resets current page index to 1 if a value greater than the total available number of pages is passed in. Why? This logic causes problems when trying to load subsequent pages of data from a paginated (but not filter-/sort-enabled) API.
*Issue #, if available:* Xw9JA4nAmlRd
=> fix: Remove condition clamping pageIndex

src/__tests__/operations/paginate.test.ts, src/interfaces.ts, src/operations/pagination.ts
*Issue #, if available:*
Revision of #99 so that the new logic is behind a flag, as the change turned out to be breaking for some customers.
=> fix: Hide new pageIndex logic behind flag

src/types.ts, src/utils.ts
*Issue #, if available:*
Unblock https://github.com/cloudscape-design/actions/pull/71
Currently `npm run lint` fails when building the main branch
=> chore: Fix linter errors
